/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IFasAddressBook: typeof import('~icons/fa6-solid/address-book')['default']
    IFasDownload: typeof import('~icons/fa6-solid/download')['default']
    IFasEye: typeof import('~icons/fa6-solid/eye')['default']
    IFasPlay: typeof import('~icons/fa6-solid/play')['default']
    IIcRoundSearch: typeof import('~icons/ic/round-search')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
